services:
  ollama:
    image: ollama/ollama
    restart: always
    container_name: ollama
    ports:
      - "11434:11434"
    networks:
      - ollama_net
    environment:
      - OLLAMA_HOST=0.0.0.0
    volumes:
      - C:/docker_data/ollama_models:/root/.ollama
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

  mysql-db:
    image: mysql:8.0
    restart: always
    container_name: mysql-db
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=sqlagent
      - MYSQL_DATABASE=sakila
      - MYSQL_USER=sqlagent
      - MYSQL_PASSWORD=sqlagent
    volumes:
      - C:/docker_data/mysql_data:/var/lib/mysql
    networks:
      - ollama_net

networks:
  ollama_net:
    driver: bridge

volumes:
  mysql_data:
  ollama_models:
